# -*- coding: utf-8 -*-
"""NLP assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1in6sH7L5OkgukXiZSHtsX8aTbY_nxTze

Converting to lower case
"""

text = "Hello! How are you doing today? I'm doing GREAT!!!"

text_lower = text.lower()
print("After lowercase:", text_lower)

"""Removing Punctuation"""

import re

text_no_punct = re.sub(r'[^\w\s]', '', text_lower)
print("After removing punctuation:", text_no_punct)

"""Tokenizing Text"""

import nltk
nltk.download('punkt_tab')

from nltk.tokenize import word_tokenize
tokens = word_tokenize(text_no_punct)
print("After tokenization:", tokens)

"""Removing Stopwords"""

from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
filtered_tokens = [word for word in tokens if word not in stop_words]
print("After stopword removal:", filtered_tokens)